//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicAtoutV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATIMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BATIMENT()
        {
            this.SALLE = new HashSet<SALLE>();
        }
    
        public int idBati { get; set; }
        public string nomBati { get; set; }
        public Nullable<int> anConstruction { get; set; }
        public string rueBati { get; set; }
        public Nullable<int> cpBati { get; set; }
        public string telBati { get; set; }
        public string responsable { get; set; }
        public int idVille { get; set; }
    
        public virtual VILLE VILLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALLE> SALLE { get; set; }
    }
}
