//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicAtoutV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALLE()
        {
            this.TYPEOEUVRE = new HashSet<TYPEOEUVRE>();
        }
    
        public int idBati { get; set; }
        public int numSalle { get; set; }
        public string nomSalle { get; set; }
        public Nullable<int> capacite { get; set; }
        public Nullable<int> superficie { get; set; }
    
        public virtual BATIMENT BATIMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TYPEOEUVRE> TYPEOEUVRE { get; set; }
    }
}
